include: package:effective_dart/analysis_options.yaml

analyzer:
  exclude:
    - build/**
    - lib/generated/*
    - lib/icons/*
    - "*.freezed.dart"

linter:
  rules:
    public_member_api_docs: false
    type_annotate_public_apis: false
    annotate_public_apis: false
    avoid_catches_without_on_clauses: false
    lines_longer_than_80_chars: false
    prefer_relative_imports: false
    avoid_types_on_closure_parameters: false
    avoid_classes_with_only_static_members: false
    avoid_returning_null: false
    avoid_positional_boolean_parameters: false
    one_member_abstracts: false
    unnecessary_brace_in_string_interps: false
    avoid_catching_errors: false
    prefer_mixin: false

    # ------------------------------------------------------------------------ #
    # Those rules should be removed once VSCode starts respecting excluded files.
    constant_identifier_names: false
    non_constant_identifier_names: false
    omit_local_variable_types: false
    unnecessary_const: false
    avoid_equals_and_hash_code_on_mutable_classes: false
    # ------------------------------------------------------------------------ #
