name: junto_beta_mobile
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  scoped_model: ^1.0.1    
    

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  fonts:
    - family:  Avenir
      fonts:
      - asset: assets/fonts/Avenir-Medium.ttf
      - asset: assets/fonts/Avenir-Heavy.ttf
        weight: 600 
      - asset: assets/fonts/Avenir-Black.ttf
        weight: 700                

    - family:  home
      fonts:
      - asset: assets/fonts/j_home.ttf

    - family:  lotus
      fonts:
      - asset: assets/fonts/j_home.ttf  

    - family:  resonate
      fonts:
      - asset: assets/fonts/j_home.ttf

    - family:  comment
      fonts:
      - asset: assets/fonts/j_home.ttf        
      
    - family:  moon
      fonts:
      - asset: assets/fonts/j_home.ttf  

    - family:  circle
      fonts:
      - asset: assets/fonts/j_home.ttf 

    - family:  triangle
      fonts:
      - asset: assets/fonts/j_home.ttf   

    - family:  member
      fonts:
      - asset: assets/fonts/j_home.ttf   

    - family:  more
      fonts:
      - asset: assets/fonts/j_home.ttf

    - family:  MyFlutterApp
      fonts:
      - asset: assets/fonts/MyFlutterApp.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/junto-mobile__logo--collective.png
    - assets/images/junto-mobile__logo--pack.png
    - assets/images/junto-mobile__logo--den.png
    - assets/images/junto-mobile__logo--spheres.png 
    - assets/images/junto-mobile__eric.png 
    - assets/images/junto-mobile__expression--photo.png
    - assets/images/junto-mobile__den--photo.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  
  
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
